dest: xenial
# Released April 2018, Support ended: April 2023
# ruby 2.4.9, 2.5.3, 2.5.7, 2.6.5 (default) and 2.7.0 pre-installed on travis
sudo: false
addons:
  apt:
    packages:
    - net-tools

cache: bundler
language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - gem install smarter_bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  fast_finish: true

  include:
    # DROPPED rails 5.0 support as I could not be bothered fixing the error:
    # Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile
    # When sqlite3 should already be in the Gemfile
    # and rails 5.0 is no longer supported
    # -------------------------------------
    # Standard
    
    # ruby 5.0  Jun. 2016
    
#    - rvm: 2.2.2
#      gemfile: test/rails_5.0.gemfile
#      env: 
#      - RAILS_VERSION=5.0 
#      - MIDDLEWARE=no
#      - RUBYGEMS_VERSION=2.7.11
#      - BUNDLER_VERSION=1.17.3
#
#    - rvm: 2.3.6
#      gemfile: test/rails_5.0.gemfile
#      env:
#      - RAILS_VERSION=5.0
#      - MIDDLEWARE=no

    # rails 5.1 sometime before May 2017
    
    - rvm: 2.2.2
      gemfile: test/rails_5.1.gemfile
      env:
      - RAILS_VERSION=5.1
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.3.6
      gemfile: test/rails_5.1.gemfile
      env:
      - RAILS_VERSION=5.1
      - MIDDLEWARE=no
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.4.3
      gemfile: test/rails_5.1.gemfile
      env:
      - RAILS_VERSION=5.1
      - MIDDLEWARE=no

    # -------------------------------------
    # Middleware
    
    # ruby 5.0  Jun. 2016
    
#    - rvm: 2.2.2
#      gemfile: test/rails_5.0.gemfile
#      env:
#      - RAILS_VERSION=5.0
#      - MIDDLEWARE=yes
#      - RUBYGEMS_VERSION=2.7.11
#      - BUNDLER_VERSION=1.17.3
#
#    - rvm: 2.3.6
#      gemfile: test/rails_5.0.gemfile
#      env:
#      - RAILS_VERSION=5.0
#      - MIDDLEWARE=yes

    # rails 5.1 sometime before May 2017
    
    - rvm: 2.2.2
      gemfile: test/rails_5.1.gemfile
      env:
      - RAILS_VERSION=5.1
      - MIDDLEWARE=yes
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.4.3
      gemfile: test/rails_5.1.gemfile
      env:
      - RAILS_VERSION=5.1
      - MIDDLEWARE=yes


    # rails 5.2 April 2018
    
    - rvm: 2.2.2
      gemfile: test/rails_5.2.gemfile
      env:
      - RAILS_VERSION=5.2
      - MIDDLEWARE=yes
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.4.3
      gemfile: test/rails_5.2.gemfile
      env:
      - RAILS_VERSION=5.2
      - MIDDLEWARE=yes

