dist: focal
# Released April 2020, Support ended: April 2025
# ruby 2.5.7, 2.5.8, 2.6.5, 2.6.6, 2.7.0 and 2.7.1 pre-installed on travis
sudo: false
addons:
  apt:
    packages:
    - net-tools

cache: bundler
language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - gem install smarter_bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  fast_finish: true

  allow_failures:
    - rvm: 3.0.1
      gemfile: test/rails_edge.gemfile
      env:
      - RAILS_VERSION=edge
      - MIDDLEWARE=YES

    - rvm: ruby-head
      gemfile: test/rails_edge.gemfile
      env:
      - RAILS_VERSION=edge
      - MIDDLEWARE=YES

  include:
    - rvm: 2.5.0
      gemfile: test/rails_6.0.gemfile
      env:
      - RAILS_VERSION=6.0
      - MIDDLEWARE=YES

    - rvm: 2.6.7
      gemfile: test/rails_6.0.gemfile
      env:
      - RAILS_VERSION=6.0
      - MIDDLEWARE=YES

    - rvm: 2.7.1
      gemfile: test/rails_6.0.gemfile
      env:
      - RAILS_VERSION=6.0
      - MIDDLEWARE=YES

    - rvm: 2.5.0
      gemfile: test/rails_6.1.gemfile
      env:
      - RAILS_VERSION=6.1
      - MIDDLEWARE=YES

    - rvm: 2.6.6
      gemfile: test/rails_6.1.gemfile
      env:
      - RAILS_VERSION=6.1
      - MIDDLEWARE=YES

    - rvm: 2.7.3
      gemfile: test/rails_6.1.gemfile
      env:
      - RAILS_VERSION=6.1
      - MIDDLEWARE=YES

    - rvm: 3.0.1
      gemfile: test/rails_6.1.gemfile
      env:
      - RAILS_VERSION=6.1
      - MIDDLEWARE=YES

#    - rvm: 2.5.0
#      gemfile: test/rails_6.2.gemfile
#      env:
#      - RAILS_VERSION=6.2
#      - MIDDLEWARE=YES
#
#    - rvm: 2.6.6
#      gemfile: test/rails_6.2.gemfile
#      env:
#      - RAILS_VERSION=6.2
#      - MIDDLEWARE=YES
#
#    - rvm: 2.7.3
#      gemfile: test/rails_6.2.gemfile
#      env:
#      - RAILS_VERSION=6.2
#      - MIDDLEWARE=YES
#
#    - rvm: 3.0.1
#      gemfile: test/rails_6.2.gemfile
#      env:
#      - RAILS_VERSION=6.2
#      - MIDDLEWARE=YES
#
