sudo: false
addons:
  apt:
    packages:
    - net-tools

cache: bundler
language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  fast_finish: true

  allow_failures:
    - rvm: 2.3.1
      gemfile: test/rails_edge.gemfile
      env: RAILS_VERSION=edge MIDDLEWARE=YES

    - rvm: ruby-head
      gemfile: test/rails_5.1.gemfile
      env: RAILS_VERSION=5.1 MIDDLEWARE=YES

  include:
    - rvm: 2.3.1
      gemfile: test/rails_edge.gemfile
      env: RAILS_VERSION=edge MIDDLEWARE=YES

    - rvm: ruby-head
      gemfile: test/rails_5.1.gemfile
      env: RAILS_VERSION=5.1 MIDDLEWARE=YES

    - rvm: 2.3.1
      gemfile: test/rails_5.1.gemfile
      env: RAILS_VERSION=5.1 MIDDLEWARE=YES

